version: "3.8"
services:
  sgdata:
    build: ./data/
    networks:
        - sgnetwork
  sgapp :
    build: ./app/
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - sgdata
    links:
        - sgdata:sgdata
    networks:
        - sgnetwork
networks:
    sgnetwork:
        driver: bridge